# Generated by Django 4.1 on 2023-03-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_heros_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heros',
            new_name='Team',
        ),
    ]
